---
# These tasks install Apache web server

- name: Install Apache
  yum: name={{ item }} state=present
  with_items:
   - httpd

- name: Remove Apache default conf
  file: dest=/etc/httpd/conf.d/welcome.conf state=absent

- name: Copy Apache config
  template: src=apache.conf dest=/etc/httpd/conf.d/emergency.conf owner=root group=root mode=644

- name: restart apache
  service: name=httpd state=restarted enabled=yes