---
# This playbook deploys Whydah to AWS AMI's

- name: Set up Whydah UserIdentityBackend
  hosts: Whydah_UserIdentityBackend
  sudo: true
  roles:
    - standard
    - uib
    - whydahApp
  tags:
    uib
  vars:
    username: UserIdentityBackend
    group_id: net/whydah/identity
    app_name: UserIdentityBackend
    version: 2.0-SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    env_mode: PROD


- name: Set up Whydah SecurityTokenService
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - whydahApp
  tags:
    token
  vars:
    username: SecurityTokenService
    group_id: net/whydah/token
    app_name: SecurityTokenService
    version: 2.0.1-SNAPSHOT
    env_vars: -DIAM_MODE=PROD


- name: Set up Whydah SSOLoginWebApp
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - ssoLogin
    - whydahApp
  tags:
    sso
  vars:
    username: SSOLoginWebApp
    group_id: net/whydah/sso
    app_name: SSOLoginWebApp
    version: 2.0.1-SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    env_mode: PROD


- name: Set up Whydah UserAdminWebapp
  hosts: Whydah_UserAdminWebapp
  sudo: true
  roles:
    - userAdministration
    - whydahApp
  tags:
    adminapp
  vars:
    username: UserAdminWebapp
    group_id: net/whydah/identity
    app_name: UserAdminWebapp
    version: 0.4-SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    env_mode: PROD
    service_config: useradministration