---
# This playbook deploys Whydah to AWS AMI's

- name: Set up Whydah UserIdentityBackend
  hosts: Whydah_UserIdentityBackend
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    uib
  vars:
    username: UserIdentityBackend
    group_id: net/whydah/identity
    app_name: UserIdentityBackend
    version: SNAPSHOT
    env_mode: PROD
    env_vars: -DIAM_MODE=PROD
    service_config_template: useridentitybackend.properties
    service_config: useridentitybackend.PROD.properties
    verify_service_url: http://localhost:9995/uib/authenticate/application/
  vars_files:
    - vars/uib


- name: Set up Whydah SecurityTokenService
  hosts: Whydah_SecurityTokenService
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    sts
  vars:
    username: SecurityTokenService
    group_id: net/whydah/token
    app_name: SecurityTokenService
    applicationid: 11
    applicationsecret: 6r46g3q986Ep6By7B9J46m96D
    version: SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    service_config_template: securitytokenservice.properties
    service_config: securitytokenservice.PROD.properties
  vars_files:
    - vars/securityTokenService

- name: Set up Whydah SSOLoginWebApp
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    sso
  vars:
    username: SSOLoginWebApp
    group_id: net/whydah/sso
    app_name: SSOLoginWebApp
    version: SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    service_config_template: ssologinservice.properties
    service_config: ssologinservice.PROD.properties
    verify_service_url: http://localhost:9997/sso/login
  vars_files:
    - vars/ssoLogin

- name: Set up Whydah UserAdminWebapp
  hosts: Whydah_UserAdminWebapp
  sudo: true
  roles:
    - standard
    - configuration
    - app
  tags:
    admin
  vars:
    username: UserAdminWebapp
    group_id: net/whydah/identity
    app_name: UserAdminWebapp
    version: SNAPSHOT
    env_vars: -DIAM_MODE=PROD
    service_config_template: useradministration.properties
    service_config: useradministration.PROD.properties
    verify_service_url: http://localhost:9996/useradmin
  vars_files:
    - vars/userAdministration

- name: Set up Apache config
  hosts: Whydah_SSOLoginWebApp
  sudo: true
  roles:
    - apache
  tags:
    apache