---
- name: Set up user
  user: name={{username}} #group=?

- name: Install Java dependencies
  yum: name={{ item }} state=present
  with_items:
    - java-1.7.0-openjdk

#Async operation
#- name: yum update
#action: command yum -y update
#async: 7200
#poll: 15

- name: App update script
  template: src=update-service.sh.jinja dest=/home/{{username}}/update-service.sh mode=744
  sudo_user: "{{username}}"

- name: Fetch Latest greatest version of App
  command: /home/{{username}}/update-service.sh chdir=/home/{{username}}
  sudo_user: "{{username}}"

- name: Link latest version of app
  file: src=/home/{{username}}/{{app_name}}-{{version}}.jar dest=/home/{{username}}/{{app_name}}.jar state=link
  sudo_user: "{{username}}"

- name: App upstart conf
  template: src=service-upstart.conf.jinja dest=/etc/init/{{app_name}}.conf owner=root mode=644

- name: Start App service
  service: name="{{app_name}}" state=started